### ISSUE TITLE
Istio CRD proposal

### ISSUE THREAD

**Issue by strekm** [kyma-project/istio#11]
**Description**

Propose specification of Istio CRD based on following IstioOperator configuration:

```
  meshConfig:
    accessLogEncoding: JSON
    accessLogFile: /dev/stdout
    defaultConfig:
      gatewayTopology:
        numTrustedProxies: 1
```
Additionally for each Istio component hpa and resource configuration should be possible:
```
  components:
    ingressGateways:
    - enabled: true
        hpaSpec:
          maxReplicas: 5
          metrics:
          - resource:
              name: cpu
              targetAverageUtilization: 80
            type: Resource
          - resource:
              name: memory
              targetAverageUtilization: 80
            type: Resource
          minReplicas: 1
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 10m
            memory: 128Mi
```

**Reasons**

Support for xff

**Attachments**

part of: https://github.com/kyma-project/kyma/issues/15865

**Comment by dariusztutaj** [comment]
Proposal:
```
apiVersion: operator.kyma-project.io/v1alpha1
kind: Istio
metadata:
spec:
  controlplane:
    istiod:
      deployment:
        hpa: 
          maxReplicas: 5
          minReplicas: 2
        strategy:
          rollingUpdate:
            maxSurge: 50%
            maxUnavailable: "0"
        resources:
          limits:
            cpu: 250m
            memory: 384Mi
          requests:
            cpu: 10m
            memory: 128Mi
      meshConfig:
        gatewayTopology:
          numTrustedProxies: <VALUE>
          forwardClientCertDetails: SANITIZE|FORWARD_ONLY|APPEND_FORWARD|SANITIZE_SET|ALWAYS_FORWARD_ONLY
  dataplane:
    ingressGateway:
      deployment:
        hpa: 
          maxReplicas: 5
          minReplicas: 2
          metrics:
          - resource:
              name: cpu
              targetAverageUtilization: 80
            type: Resource
          - resource:
              name: memory
              targetAverageUtilization: 80
        strategy:
          rollingUpdate:
            maxSurge: 50%
            maxUnavailable: "0"
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
        podAffinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - istio-ingressgateway
                topologyKey: "kubernetes.io/hostname"
        annotations: {}
      service:
        ports:
        - name: status-port
          port: 15021
          targetPort: 15021
        - name: http2
          port: 80
          targetPort: 8080
        - name: https
          port: 443
          targetPort: 8443
        - name: tcp
          port: 31400
          targetPort: 31400
        annotations: {}
```

**Comment by pbochynski** [comment]
I've got another request for istio configuration - enable [DNS proxying](https://istio.io/latest/docs/ops/configuration/traffic-management/dns-proxy/)
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    defaultConfig:
      proxyMetadata:
        # Enable basic DNS proxying
        ISTIO_META_DNS_CAPTURE: "true"
        # Enable automatic address allocation, optional
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
```
Can you add it to the initial proposal?
