### ISSUE TITLE
Allow only one Istio CR

### ISSUE THREAD

**Issue by triffer** [kyma-project/istio#172]
**Description**
It is possible to create multiple Istio CR. To have a reliable reconciliation we should restrict this, so only one Istio CR can be present.
Applying the following Istio CRs will show the issue:
```
apiVersion: operator.kyma-project.io/v1alpha1
kind: Istio
metadata:
  name: istio-sample
  labels:
    app.kubernetes.io/name: istio-sample
spec:
---
apiVersion: operator.kyma-project.io/v1alpha1
kind: Istio
metadata:
  name: istio-sample-2
  labels:
    app.kubernetes.io/name: istio-sample-2
spec:
```

A possibility to restrict this can be to define a resource count quota for the Istio CR. 
https://kubernetes.io/docs/concepts/policy/resource-quotas/#object-count-quota
```
apiVersion: v1
kind: ResourceQuota
metadata:
  name: kyma-istios
spec:
  hard:
    count/istios.operator.kyma-project.io: "1"
```

The documentation of Resource quota describes that it's scoped to namespaces, but in tests applying multiple Istio CRs to different namespaces caused an error for the second Istio CR:
```
istios.operator.kyma-project.io "istio-sample-2" is forbidden: exceeded quota: kyma-istios, requested: count/istios.operator.kyma-project.io=1, used: count/istios.operator.kyma-project.io=1, limited: count/istios.operator.kyma-project.io=1
```

**Reasons**
Multiple Istio CRs will just reconcile and overwrite each other. To have a deterministic reconciliation, we should support only one Istio CR.

**DoD:**
- [x] provide documentation
~~- [ ] release notes and What's New updates for Kyma customers~~
- [x] provide unit tests
- [x] provide integration tests
- [x] test on production-like environment
- [x] verify resource limits
~~- [ ] followup issue~~
- [x] PR reviewer will verify code coverage and evaluate if it is acceptable

**PRs**
- [x] https://github.com/kyma-project/istio/pull/247
- [x] https://github.com/kyma-project/istio/pull/273

**Follow-up**
- https://github.com/orgs/kyma-project/projects/27/views/5?pane=issue&itemId=34279366

**Attachments**
