### ISSUE TITLE
Configurable access logs

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/istio#489]
**Description**
The istio module ships a hardcoded set of istio telemetry extensionProviders. One of these providers configures [access logging](https://github.com/kyma-project/istio/blob/4cf072316544821d3581e5e7432fd20d56412f6c/manifests/istio-operator-template.yaml#L163) based on stdout using a fixed JSON format. Using the extensionProvider mechanism users can selectively enable access logging on workloads or a gateway.

Users have custom request and response headers used across solutions and with that like to have them included in the access logs as well. As far as I can see is the existing approach of logging to stdout accepted, still istio already supports logging via OTLP. In combination with the strategy of the telemetry module (https://github.com/kyma-project/telemetry-manager/issues/556), any customization should be also possible following the OTLP approach in future.

So one aspect is the actual format configuration, the other the actual backend configuration (here stdout). Thinking of traces and metrics, it becomes relevant on what the focus of the configurability will be. Having multiple formats specifiable and then assigned to different workloads could be a requirement as well.

**Goal**
Turn the access logging into a configurable feature, supporting at least additional request and response headers. In best case you can define your own format. The feature should work with a solution based on OTLP as well. Aspects like traces and metrics could be supported in a similar way.

**Actions**
- [ ] Propose solutions and outline pros and cons
- [ ] Make PoC and come to a documented decision
- [ ] Implement and document the feature

**Reasons**
Access logs are often a key element for monitoring. If relevant context is encoded in headers, users require to see that context in the logs to improve the observability. 

**Attachments**

**Comment by a-thaler** [comment]
After a first discussion round, it seems most valuable to focus on supporting well-defined and preconfigured extensionProviders which can be configured via the modules API. So taking the existing provider based on json and stdout and make the format extensible, having in mind that additional providers might be added later for further scenarios which again can be configured.
Hereby, we see it more important to support well-defined integration scenarios which are tested very well instead of providing full flexibility leveraging providers like envoyHttpAls which are barely tested by the module.
A more concrete API proposal will follow as a next step.

**Comment by videlov** [comment]
We brainstormed different options and came up with this simple proposal. We would like to extend Istio CR's spec with additional configuration for Istio's `MeshConfig`.

We will have two default Istio [extension providers](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig-ExtensionProvider) definitions for [EnvoyFileAccessLogProvider](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig-ExtensionProvider-EnvoyFileAccessLogProvider) and [EnvoyOpenTelemetryLogProvider](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig-ExtensionProvider-EnvoyOpenTelemetryLogProvider) to emit access logs either in JSON to stdout or OTLP.

The defined access log format is applied to all extension providers. The user activates an extension provider for specific workloads or the entire service mesh using the telemetry API.

*Example*

```yaml
apiVersion: operator.kyma-project.io/v1alpha1
kind: Istio
metadata:
  name: default
  namespace: kyma-system
spec:
  config:
    accessLog:
      strategy: "merge" | "replace"
      format:
        tenant: "%REQ(X-TENANT)%"
```

- `strategy` defines how to apply the key-value map in `format`. either `merge` with the existing [default configuration](https://github.com/kyma-project/istio/blob/f5e3db5becb4947a14dcf93e0916a4ebf37f06c2/manifests/istio-operator-template.yaml#L167-L197) or `replace` it with a completely new custom one
- `format` refers to [LogFormat](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig-ExtensionProvider-EnvoyFileAccessLogProvider-LogFormat)'s `labels`

**Comment by a-thaler** [comment]
Additional background to the discussion: Activating multiple providers for access logs at the same time is unlikely as the outputs are usually conflicting (on stdout for sure, on OTLP potentially). So the user mainly wants to influence the format and then select the pre-defined output format. We do not see the need at the moment that other output types need to be configurable.
Leveraging an OTLP integration via the telemetry module in future will even provide manipulation options at a later stage.

**Comment by a-thaler** [comment]
In case you cannot wait for the feature, there is a workaround to have an additional access log configuration in the EnvoyFilter. This will be a configuration independent to the one which you can enable by the telemetry resource, so the easiest way to avoid duplicate log entries is to not enable access logging using the istio telemetry resources and to add all relevant fields in the EnvoyFilter configuration taken from [here](https://github.com/kyma-project/istio/blob/fd34803dd516c3b614fda4f5b9d9a4c8b46372bb/manifests/istio-operator-template.yaml#L169).

The following example will add a new log attribute with the fields tenant_id, method, path, traceparent, tracestate for HTTP requests that are inbound to the sidecar with the label app: `httpbin`.
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: tenant-access-log
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: httpbin
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: MERGE
        value:
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
            access_log:
              - name: envoy.access_loggers.file
                typed_config:
                  "@type": "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog"
                  path: /dev/stdout
                  logFormat:
                    jsonFormat:
                      tenant_id: "%REQ(X-Tenant-ID)%"
                      method: "%REQ(:METHOD)%"
                      path: "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
                      traceparent: "%REQ(TRACEPARENT)%"
                      tracestate: "%REQ(TRACESTATE)%"
```
Sending a http request to the workload with the header `X-TENANT-ID:3213` set will result in the log for the default log configuration and an additional log containing the tenant ID.
```json
{"method":"GET","traceparent":null,"tenant_id":"3213","tracestate":null,"path":"/anything"}
```
