### ISSUE TITLE
Proxies that can't be restarted are blocking Ingress Gateway restart

### ISSUE THREAD

**Issue by triffer** [kyma-project/istio#534]
**Description**

Part of the reconciliation is restarting the Istio proxy sidecars if they are running an outdated version. If there are workloads that can't be restarted by the controller, the Istio CR will be set to warning. In this case, also the reconciliation is stopped and requeued. 
In the current implementation the restart of the ingress gateway is executed after the execution of the proxy restart. This can result in a state, where the ingress gateway restart is not executed until the proxy restart warning is fixed.

In the current state the ingress gateway restart only has one predicate(creation of kyma-refefer EnfoyFilter), so it might not be a big problem. But when more predicates for the restart are added, this might become a bigger issue.

We should adapt this implementation, so a warning from the proxy reset will not exclude the execution of following reconciliation steps. Additionally, depending on what we implemented and learned, we should extend the changes to the reconciliation flow in technical design documentation.

**Expected result**

Ingress gateway restart is executed when the Istio CR is in warning state due to `Istio controller could not restart one or more istio-injected pods.`.

**Actual result**

Ingress gateway restart is not restarted.

**Steps to reproduce**

- Install Istio module with an older Istio version
- Enable istio injection in default namespace `kubectl label namespace default istio-injection=enabled --overwrite`
- Create a job in the namespace with Istio injection enabled
```
apiVersion: batch/v1
kind: Job
metadata:
  name: httpbin-job
spec:
  template:
    metadata:
      labels:
        app: httpbin-job
        version: v1
    spec:
      #serviceAccountName: httpbin
      restartPolicy: OnFailure
      containers:
        - image: docker.io/kennethreitz/httpbin
          imagePullPolicy: IfNotPresent
          name: httpbin
          ports:
            - containerPort: 80
```
- Install module with updated version of Istio
- Istio CR should be in warning state, because of

TODOS:  (@kolodziejczak)
- [x] Introduce Restarter concept
- [x] Move conditions creation down to the restarters
- [x] Unit tests
- [x] Update architectural design docs
~~- [ ] Integration tests~~
