### ISSUE TITLE
Connectivity issues on Openstack clusters due to proxy protocol

### ISSUE THREAD

**Issue by triffer** [kyma-project/istio#688]
**Description**
There is an issue with connectivity on Openstack clusters. This issue is related to the X-Forwarded-For header, more precisely the proxy protocol that is used to forward the client IP. The Istio module applies an [EnvoyFilter to handle the proxy protocol](https://github.com/kyma-project/istio/blob/main/internal/reconciliations/istio_resources/proxy_protocol_envoy_filter.yaml). 

This filter should be only applied on AWS instances. To determine if running on AWS, the Istio module queries the [AWS instance metadata service (IMDS)](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html).
The problem is that Openstack supports two APIs for its [IMDS](https://docs.openstack.org/nova/rocky/user/metadata-service.html), an Openstack metadata API and the EC2 metadata API.

For this reason the Istio module will create an EnvoyFilter proxy protocol. If the proxy protocol EnvoyFilter is applied and the request does not contain the proxy protocol the requests will be discarded.

**Expected result**

Connection to exposed workloads is working.

**Actual result**

Connection to exposed workloads results in `Connection reset by peer`.

**Steps to reproduce**

1. Enable istio module
2. Deploy httpbin app
3. Create VirtualService to expose httpbin
4. Call exposed domain

**Troubleshooting**
Apply the following EnvoyFilter to remove the proxy_protocol filter from the listener chain.
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: remove-proxy-protocol
  namespace: istio-system
spec:
  configPatches:
  - applyTo: LISTENER_FILTER
    match:
      listener:
        listenerFilter: "proxy_protocol"
    patch:
      operation: REMOVE
  workloadSelector:
    labels:
      istio: ingressgateway
```

**PR**
- https://github.com/kyma-project/istio/pull/700
